{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c2db493a-7f4a-4d7f-990b-84682ea0e7e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "import sqlite3\n",
    "import re\n",
    "import random\n",
    "import string\n",
    "import matplotlib.pyplot as plt\n",
    "import smtplib\n",
    "\n",
    "# ===================== DATABASE SETUP =====================\n",
    "conn = sqlite3.connect(\"passwords.db\")\n",
    "cursor = conn.cursor()\n",
    "\n",
    "cursor.execute(\"\"\"\n",
    "CREATE TABLE IF NOT EXISTS password_logs (\n",
    "    id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "    password TEXT,\n",
    "    score INTEGER,\n",
    "    risk_level TEXT\n",
    ")\n",
    "\"\"\")\n",
    "\n",
    "conn.commit()\n",
    "\n",
    "# ===================== BREACH DATABASE (SIMULATED) =====================\n",
    "breached_passwords = [\"123456\", \"password\", \"admin\", \"qwerty\", \"letmein\"]\n",
    "\n",
    "# ===================== PASSWORD ANALYZER =====================\n",
    "def analyze_password(password):\n",
    "    score = 5\n",
    "    issues = []\n",
    "\n",
    "    if len(password) < 8:\n",
    "        score -= 1\n",
    "        issues.append(\"Too short\")\n",
    "\n",
    "    if not re.search(r\"[A-Z]\", password):\n",
    "        score -= 1\n",
    "        issues.append(\"No uppercase\")\n",
    "\n",
    "    if not re.search(r\"[a-z]\", password):\n",
    "        score -= 1\n",
    "        issues.append(\"No lowercase\")\n",
    "\n",
    "    if not re.search(r\"[0-9]\", password):\n",
    "        score -= 1\n",
    "        issues.append(\"No numbers\")\n",
    "\n",
    "    if not re.search(r\"[!@#$%^&*()]\", password):\n",
    "        score -= 1\n",
    "        issues.append(\"No special characters\")\n",
    "\n",
    "    if password.lower() in breached_passwords:\n",
    "        score = 0\n",
    "        issues.append(\"COMMON PASSWORD DETECTED\")\n",
    "\n",
    "    if score >= 4:\n",
    "        level = \"LOW RISK\"\n",
    "    elif score >= 2:\n",
    "        level = \"MEDIUM RISK\"\n",
    "    else:\n",
    "        level = \"HIGH RISK\"\n",
    "\n",
    "    return score, level, issues\n",
    "\n",
    "# ===================== BREACH CHECK =====================\n",
    "def check_breach(password):\n",
    "    return password.lower() in breached_passwords\n",
    "\n",
    "# ===================== SAVE TO DATABASE =====================\n",
    "def save_to_db(password, score, level):\n",
    "    cursor.execute(\n",
    "        \"INSERT INTO password_logs (password, score, risk_level) VALUES (?, ?, ?)\",\n",
    "        (password, score, level)\n",
    "    )\n",
    "    conn.commit()\n",
    "\n",
    "# ===================== NORMAL PASSWORD GENERATOR =====================\n",
    "def generate_password():\n",
    "    words = [\"sun\", \"blue\", \"river\", \"code\", \"lion\", \"cloud\", \"star\", \"tech\"]\n",
    "    pwd = random.choice(words) + str(random.randint(10, 99))\n",
    "    entry.delete(0, tk.END)\n",
    "    entry.insert(0, pwd)\n",
    "\n",
    "# ===================== EMAIL ALERT (SIMULATION) =====================\n",
    "def send_email_alert(password, level):\n",
    "    if level == \"HIGH RISK\":\n",
    "        print(\"ALERT: High-risk password detected (email simulation)\")\n",
    "\n",
    "# ===================== ANALYTICS DASHBOARD =====================\n",
    "def show_analytics():\n",
    "    cursor.execute(\"SELECT risk_level FROM password_logs\")\n",
    "    data = cursor.fetchall()\n",
    "\n",
    "    low = sum(1 for d in data if d[0] == \"LOW RISK\")\n",
    "    medium = sum(1 for d in data if d[0] == \"MEDIUM RISK\")\n",
    "    high = sum(1 for d in data if d[0] == \"HIGH RISK\")\n",
    "\n",
    "    plt.bar([\"Low\", \"Medium\", \"High\"], [low, medium, high])\n",
    "    plt.title(\"SOC Password Risk Distribution\")\n",
    "    plt.show()\n",
    "\n",
    "# ===================== MAIN ANALYSIS =====================\n",
    "def analyze():\n",
    "    password = entry.get()\n",
    "\n",
    "    if not password:\n",
    "        messagebox.showerror(\"Error\", \"Enter a password\")\n",
    "        return\n",
    "\n",
    "    score, level, issues = analyze_password(password)\n",
    "    breached = check_breach(password)\n",
    "\n",
    "    if breached:\n",
    "        level = \" CRITICAL BREACH DETECTED\"\n",
    "\n",
    "    save_to_db(password, score, level)\n",
    "    send_email_alert(password, level)\n",
    "\n",
    "    result = f\"\"\"\n",
    "Password: {password}\n",
    "Score: {score}/5\n",
    "Risk Level: {level}\n",
    "Issues: {', '.join(issues)}\n",
    "Breached: {\"YES\" if breached else \"NO\"}\n",
    "\"\"\"\n",
    "\n",
    "    messagebox.showinfo(\"SOC ANALYSIS RESULT\", result)\n",
    "\n",
    "# ===================== HACKER STYLE GUI =====================\n",
    "app = tk.Tk()\n",
    "app.title(\"SOC Security Terminal\")\n",
    "app.geometry(\"600x420\")\n",
    "app.configure(bg=\"#0b0f14\")\n",
    "\n",
    "# HEADER\n",
    "header = tk.Label(\n",
    "    app,\n",
    "    text=\"🛡 SOC PASSWORD ANALYZER TERMINAL\",\n",
    "    font=(\"Consolas\", 16, \"bold\"),\n",
    "    fg=\"#00ff9f\",\n",
    "    bg=\"#0b0f14\"\n",
    ")\n",
    "header.pack(pady=15)\n",
    "\n",
    "# FRAME\n",
    "frame = tk.Frame(app, bg=\"#111827\", bd=2, relief=\"ridge\")\n",
    "frame.pack(pady=10, padx=20, fill=\"both\", expand=True)\n",
    "\n",
    "# LABEL\n",
    "tk.Label(\n",
    "    frame,\n",
    "    text=\"ENTER PASSWORD:\",\n",
    "    font=(\"Consolas\", 12),\n",
    "    fg=\"#00ff9f\",\n",
    "    bg=\"#111827\"\n",
    ").pack(pady=10)\n",
    "\n",
    "# ENTRY\n",
    "entry = tk.Entry(\n",
    "    frame,\n",
    "    width=35,\n",
    "    font=(\"Consolas\", 14),\n",
    "    bg=\"#0b0f14\",\n",
    "    fg=\"#00ff9f\",\n",
    "    insertbackground=\"#00ff9f\",\n",
    "    relief=\"flat\"\n",
    ")\n",
    "entry.pack(pady=5)\n",
    "\n",
    "# BUTTON STYLE\n",
    "def make_button(text, command):\n",
    "    return tk.Button(\n",
    "        frame,\n",
    "        text=text,\n",
    "        command=command,\n",
    "        font=(\"Consolas\", 11, \"bold\"),\n",
    "        bg=\"#00ff9f\",\n",
    "        fg=\"#0b0f14\",\n",
    "        activebackground=\"#00cc7a\",\n",
    "        activeforeground=\"black\",\n",
    "        relief=\"flat\",\n",
    "        width=25,\n",
    "        pady=5\n",
    "    )\n",
    "\n",
    "# BUTTONS\n",
    "make_button(\" ANALYZE PASSWORD\", analyze).pack(pady=8)\n",
    "make_button(\" GENERATE PASSWORD\", generate_password).pack(pady=8)\n",
    "make_button(\" SHOW ANALYTICS\", show_analytics).pack(pady=8)\n",
    "\n",
    "# FOOTER\n",
    "tk.Label(\n",
    "    app,\n",
    "    text=\"SOC Simulation System v1.0 | Developed by SM NTIBO\",\n",
    "    font=(\"Consolas\", 10),\n",
    "    fg=\"#666\",\n",
    "    bg=\"#0b0f14\"\n",
    ").pack(side=\"bottom\", pady=10)\n",
    "app.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a57e584-3e38-4e2c-a7af-efc53e82f3d6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
